routes/web.php
<?php


use Illuminate\Support\Facades\Auth;
use Illuminate\Support\Facades\Route;
use App\Http\Controllers\PDFController;
use App\Http\Controllers\AreaController;
use App\Http\Controllers\RoleController;
use App\Http\Controllers\UserController;
use App\Http\Controllers\EventController;
use App\Http\Controllers\PuestoController;
use App\Http\Controllers\EmpresaController;
use App\Http\Controllers\HorarioController;
use App\Http\Controllers\JornadaController;
use App\Http\Controllers\EmpleadoController;
use App\Http\Controllers\HoraExtraController;
use App\Http\Controllers\AsistenciaController;
use App\Http\Controllers\TipoEventoController;
use App\Http\Controllers\DepartamentoController;
use App\Http\Controllers\Auth\RegisterController;
use App\Http\Controllers\IncidenciaHorariaController;


Route::get('/', function () {    
    if (Auth::user() != null) {
        return view('partials.admin');
    }else{
        return view('auth.login');
    }
    
});



Route::get('/admin', function () {
    return view('partials.admin');
});

Route::post('/registrar', [RegisterController::class, 'register'])->name('register.registrar');


//Inasistencia Automatica
Route::get('/inasistencia/add', [IncidenciaHorariaController::class, 'add'])->name('inasistencia.add');

//Empleados
Route::put('/empleadoalta/{empleado}', [EmpleadoController::class, 'alta'])->name('empleado.alta');
Route::get('/empleado/createfind', [EmpleadoController::class, 'createfind'])->name('empleado.createfind');
//Asistencias
Route::get('/asistencia/add', [AsistenciaController::class, 'add'])->name('asistencia.add');
Route::get('/asistencia/marcar', [AsistenciaController::class, 'marcar'])->name('asistencia.marcar');
Route::get('/jornada/editmodal', [JornadaController::class, 'editModal'])->name('jornada.editModal');

//PDF
Route::post('/generate-pdf', [PDFController::class, 'generatePDF'])->name('pdf.generar');
Route::get('/reporte/seleccionar-empleado', [PDFController::class, 'seleccionarEmpleado'])->name('pdf.seleccionar');

//Mis horarios personales
Route::get('/horario/mis_horarios',[HorarioController::class,'indexPersonal'])->name('horario.index_personal');

//Rutas Resource
Route::resource('/empresa', EmpresaController::class);
Route::resource('/area', AreaController::class);
Route::resource('/departamento', DepartamentoController::class);
Route::resource('/puesto', PuestoController::class);
Route::resource('/empleado', EmpleadoController::class);
Route::resource('/tipoevento', TipoEventoController::class);
Route::resource('/horario', HorarioController::class);
Route::resource('/jornada', JornadaController::class);
Route::resource('/horaextra', HoraExtraController::class);
Route::resource('/asistencia', AsistenciaController::class);
Route::resource('/user', UserController::class);
Route::resource('/role', RoleController::class);

//Rutas de Eventos/Incidencias
Route::delete('/event/{event}', [EventController::class, 'destroy'])->name('event.destroy');
Route::post('/event/store', [EventController::class, 'store'])->name('event.store');
Route::get('/event/create', [EventController::class, 'create'])->name('event.create');
Route::get('/event/create2', [EventController::class, 'create2'])->name('event.create2');
Route::get('/event/{event}/edit', [EventController::class, 'edit'])->name('event.edit');
Route::put('/event/{event}', [EventController::class, 'update'])->name('event.update');
Route::get('/event/mostrar', [EventController::class, 'mostrar'])->name('event.mostrar');
Route::get('/event/personal', [EventController::class, 'personal'])->name('event.personal');
Route::get('/eventper', [EventController::class, 'indexper'])->name('event.indexper');
Route::get('/event', [EventController::class, 'index'])->name('event.index');
Route::get('/events', [EventController::class, 'index2'])->name('event.index2');
Route::get('/event/{event}', [EventController::class, 'show'])->name('event.show');
Route::post('/event/editar/{id}', [EventController::class, 'editar'])->name('event.editar');
Route::get('/eventpersonal', [EventController::class, 'indexPersonal'])->name('event.indexpersonal');
Route::get('/eventpersonal/{event}', [EventController::class, 'showPersonal'])->name('event.showpersonal');

//Rutas de incidencias personales
Route::delete('/event2/{event}', [EventController::class, 'destroy2'])->name('event.destroy2');
Route::post('/event/store2', [EventController::class, 'store2'])->name('event.store2');
Route::get('/event/{event}/edit2', [EventController::class, 'edit2'])->name('event.edit2');
Route::put('/event2/{event}', [EventController::class, 'update2'])->name('event.update2');
Route::get('/events2', [EventController::class, 'index3'])->name('event.index3');
Route::get('/event2/{event}', [EventController::class, 'show2'])->name('event.show2');
Route::post('/event/editar/{id}', [EventController::class, 'editar'])->name('event.editar');
Route::get('/eventsall', [EventController::class, 'allIndex'])->name('event.all_index');
Route::get('/eventsall/{event}', [EventController::class, 'showAll'])->name('event.show_all');


//Route::get('/asistencia/marcar/{}', [AsistenciaController::class, 'marcar'])->name('asistencia.marcar');


//Horarios
//Route::get('/horarios-personal', [HorarioController::class, 'indexPersonal'])->name('horario.index_personal');


//Jornada
Route::post('/jornada/add/{horario}', [JornadaController::class, 'add'])->name('jornada.add');
Route::put('/jornada/update2/{jornada}', [JornadaController::class, 'update2'])->name('jornada.update2');




//IncidenciaHoraria-tardanza
Route::get('/incidencia-horaria-personal/index/{flag}', [IncidenciaHorariaController::class, 'indexPersonal'])->name('incidenciahoraria.index_personal');

Route::get('/incidencia-horaria/index/{flag}', [IncidenciaHorariaController::class, 'index'])->name('incidenciahoraria.index');
Route::get('/incidencia-horaria/create/{flag}', [IncidenciaHorariaController::class, 'create'])->name('incidenciahoraria.create');
Route::delete('/incidencia-horaria/{incidenciahoraria}', [IncidenciaHorariaController::class, 'destroy'])->name('incidenciahoraria.destroy');
Route::post('/incidencia-horaria/store', [IncidenciaHorariaController::class, 'store'])->name('incidenciahoraria.store');
Route::get('/incidencia-horaria/{incidenciahoraria}/edit', [IncidenciaHorariaController::class, 'edit'])->name('incidenciahoraria.edit');
Route::put('/incidencia-horaria/{incidenciahoraria}', [IncidenciaHorariaController::class, 'update'])->name('incidenciahoraria.update');
Route::get('/incidencia-horaria-personal/{incidenciahoraria}', [IncidenciaHorariaController::class, 'personal'])->name('incidenciahoraria.personal');
Route::get('/incidencia-horaria/{incidenciahoraria}', [IncidenciaHorariaController::class, 'show'])->name('incidenciahoraria.show');

//IncidenciaHoraria-retiros tempranos

//Ruta de Asistencias
// Index personal
Route::get('/mis-asistencias',[AsistenciaController::class, 'index'])->name('asistencia.index');
// Index general
Route::get('/lista-asistencias',[AsistenciaController::class,'indexAll'])->name('asistencia.indexall');
Route::get('/asistencia/{id}',[AsistenciaController::class, 'show'])->name('asistencia.show');
Route::get('/lista-asistencias/create',[AsistenciaController::class,'create'])->name('asistecia.create');
Route::post('lista-asistencias/store',[AsistenciaController::class,'store'])->name('asistencia.store');
Route::get('lista-asistencias/{asistencia}/edit',[AsistenciaController::class,'edit'])->name('asistencia.edit');
Route::put('lista-asistencias/{asistencia}',[AsistenciaController::class,'update'])->name('asistencia.update');
Route::delete('lista-asistencias/{asistencia}',[AsistenciaController::class,'destroy'])->name('asistencia.destroy');

//Horas Extras
Route::get('/horas-extras-personal', [HoraExtraController::class, 'indexPersonal'])->name('horaextra.index_personal');








Auth::routes();

Route::get('/home', [App\Http\Controllers\HomeController::class, 'index'])->name('home');

app/Models/Departamento.php
<?php

namespace App\Models;

use App\Models\Puesto;
use Illuminate\Database\Eloquent\Model;
use Illuminate\Database\Eloquent\Factories\HasFactory;

class Departamento extends Model
{

    Protected $fillable = ['nombre','area_id'];


    public function area()
    {
    	return $this->belongsTo(Area::class);
    }

    public function puestos()
    {
        return $this->hasMany(Puesto::class);
    }
    use HasFactory;
}

app/Http/Controllers/DepartamentoController.php
<?php

namespace App\Http\Controllers;

use App\Models\Area;
use App\Models\Departamento;
use Illuminate\Http\Request;
use Illuminate\Support\Facades\Redirect;
use App\Http\Requests\StoreDepartamentoPost;

class DepartamentoController extends Controller
{

    public function __construct(){
        $this->middleware('can:departamento.index')->only('index');
        $this->middleware('can:departamento.edit')->only('edit', 'update');
        $this->middleware('can:departamento.destroy')->only('destroy');
        $this->middleware('can:departamento.create')->only('create', 'store');
        $this->middleware('can:departamento.show')->only('show');    
    }
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        $departamentos = Departamento::orderBy('created_at','desc')->paginate(10);
        return view("departamento/index",['departamentos' => $departamentos]);
    }

    /**
     * Show the form for creating a new resource
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        $areas = Area::get();

        return view("departamento/create",["departamento" => new Departamento(), "areas" => $areas]);
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(StoreDepartamentoPost $request)
    {
        Departamento::create($request->validated());
        return Redirect::to("departamento")->with('status','Departamento Creado Exitosamente'); 
    }

    /**
     * Display the specified resource.
     *
     * @param  \App\Models\Departamento  $departamento
     * @return \Illuminate\Http\Response
     */
    public function show(Departamento $departamento)
    {
        return view("departamento.show", ["departamento" => $departamento]);
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  \App\Models\Departamento  $departamento
     * @return \Illuminate\Http\Response
     */
    public function edit(Departamento $departamento)
    {
        $areas = Area::get();
        return view("departamento.edit", ["departamento" => $departamento, "areas" => $areas]);
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  \App\Models\Departamento  $departamento
     * @return \Illuminate\Http\Response
     */
    public function update(StoreDepartamentoPost $request, Departamento $departamento)
    {
        $departamento->update($request->validated());
        return Redirect::to("departamento")->with('status','Departamento Actualizado');
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  \App\Models\Departamento  $departamento
     * @return \Illuminate\Http\Response
     */
    public function destroy(Departamento $departamento)
    {        
        if($departamento->puestos->count() == 0){
            $departamento->delete();
            return back()->with('status','Departamento Eliminado');
        }else{
            return back()->with('error','No puede eliminarse el departamento ya que tiene información asociada'); 
        }
    }



}

resources/views/departamento/_form.blade.php
@csrf
<div class="card">
    <div class="card-body">
<div class="row">
<div class="form-group col-md-6 mb-3">
    <label for="nombre">Nombre</label>
    <input class="form-control form-control-sm" type="text" name="nombre" id="nombre" value="{{ old('nombre', $departamento->nombre)}}" required autofocus>

    @error('nombre')
    <small class="text-danger">{{ $message }}</small>
    @enderror   

</div>
</div>

<div class="row">
<div class="form-group col-md-6 mb-3">
    <label for="area_id">Area</label>
    <select class="form-control form-control-sm" name="area_id" id="area_id">
        @foreach ($areas as $area)
            <option {{ $departamento->area_id == $area->id ? 'selected="selected"' : ''}} value="{{ $area->id}}">{{ $area->nombre}}</option>
        @endforeach
    </select>
    
    @error('area_id')
    <small class="text-danger">{{ $message }}</small>
    @enderror   
</div>
</div>

<div class="row col-md-6 mb-3">
<input class="btn btn-primary" type="submit" value="Guardar">
</div>
</div>
</div>
{{-- <script>
    $(document).ready(function() {
        $('#area_id').select2();
    });

    $(document).on('select2:open', () => {
    document.querySelector('.select2-search__field').focus();
  });
</script> --}}

resources/views/departamento/create.blade.php
@extends('partials.admin')


@section('content')
<div class="row d-flex flex-row">
    <div class="p-2">
        <h3 class="text-primary">Registrar un Departamento</h3>
    </div>
    <div class="ml-auto p-2 d-flex align-items-center">
        <a href="{{ route('departamento.index') }}">
            <button class="btn btn-info btn-circle"><i class="fa fw fa-arrow-left"></i></button>
        </a>
    </div>
</div>

{{-- @include('partials.validation-error') --}}

<form action="{{  route("departamento.store")  }}" method="post">
@include('departamento._form')
</form>

@endsection

resources/views/departamento/edit.blade.php
@extends('partials.admin')


@section('content')
<div class="row d-flex flex-row">
    <div class="p-2">
        <h3 class="text-primary">Editar un Departamento</h3>
    </div>
    <div class="ml-auto p-2 d-flex align-items-center">
        <a href="{{ route('departamento.index') }}">
            <button class="btn btn-info btn-circle"><i class="fa fw fa-arrow-left"></i></button>
        </a>
    </div>
</div>
@include('partials.validation-error')

<form action="{{  route("departamento.update", $departamento->id)  }}" method="post">
    @method('PUT')
    @include('departamento._form')
</form>
<br>

@endsection

resources/views/departamento/index.blade.php
@extends('partials.admin')



@section('content')
<div class="row d-flex flex-row">
    <div class="p-2">
        <h3 class="text-primary">Listado de Departamentos</h3>
    </div>
</div>

{{-- <a class="btn btn-success mt-3 mb-3" href="{{ route('empresa.create') }}">Crear</a> --}}


@include('partials.session-status')
@include('partials.session-error')
<p class="alert alert-info d-none d-sm-block animated fadeIn" >
    Desde aquí, podrá <strong>crear, editar</strong> o <strong>dar de baja</strong> un Departamento.
</p>
<table class="table table-bordered table-hover table-responsive-sm shadow table-sm">
    <thead class="bg-dark text-white">
        <tr>
            <td>
                Id
            </td>
            <td>
                Nombre
            </td>
            <td>
                Area    
            </td>          
            <td>
                <div class="d-flex justify-content-center">
                    <a href="{{ route('departamento.create') }}" >
                        <button class="btn btn-success btn-sm" type="button"><i class="fa fw fa-plus"></i> Nuevo</button>
                    </a>
                </div>
            </td>
        </tr>
    </thead>
    <tbody>
        @if($departamentos->count() == 0)
            <td style="background-color:gainsboro" colspan="5">No hay departamentos registrados</td>
        @else
       @foreach ( $departamentos as $departamento)
       <tr>
            <td>
                {{ $departamento->id }}
            </td>
            <td>
                {{ $departamento->nombre }}
            </td>
            <td>
                {{ $departamento->area->nombre }}
            </td>
            <td>
                <div class="d-flex justify-content-center">
                <a href="{{ route('departamento.show', $departamento->id)}}" class="btn btn-primary mr-2 btn-sm"><i class="fa fw fa-info"></i> Ver</a>
                <a href="{{ route('departamento.edit', $departamento->id)}}" class="btn btn-warning mr-2 btn-sm"><i class="fa fw fa-edit"></i> Editar</a>
                
                <button type="button" class="btn btn-danger btn-sm" data-toggle="modal" data-target="#deleteModal" data-id="{{ $departamento->id }}"><i class="fas fa-trash"></i> Eliminar</button>
                </div>
            </td>
        </tr>
        @endforeach
        @endif
    </tbody>
</table>

{{ $departamentos->links() }}

<div class="modal fade" id="deleteModal" tabindex="-1" role="dialog" aria-labelledby="exampleModalLabel"
    aria-hidden="true">
    <div class="modal-dialog" role="document">
        <div class="modal-content">
            <div class="modal-header">
                <h5 class="modal-title" id="modalLabel"></h5>
                <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                    <span aria-hidden="true">&times;</span>
                </button>
            </div>
            <div class="modal-body">
                <p>¿Seguro que desea borrar el registro seleccionado?</p>
            </div>
            <div class="modal-footer">
                <button type="button" class="btn btn-secondary" data-dismiss="modal">Close</button>
                <form  id="formDelete" action="{{ route('departamento.destroy',0) }}" method="POST" data-action="{{ route('departamento.destroy',0) }}">
                    @method('DELETE')
                    @csrf
                    <button type="submit" class="btn btn-danger"><i class="fas fa-trash"></i> Eliminar</button>
                </form>
            </div>
        </div>
    </div>
</div>

<script>
    window.onload = function() {
    $('#deleteModal').on('show.bs.modal', function (event) {  
  var button = $(event.relatedTarget) // Button that triggered the modal
  var id = button.data('id') // Extract info from data-* attributes
  // If necessary, you could initiate an AJAX request here (and then do the updating in a callback).
  // Update the modal's content. We'll use jQuery here, but you could use a data binding library or other methods instead.
  action = $('#formDelete').attr('data-action').slice(0,-1)
  action += id
  console.log(action)

  $('#formDelete').attr('action', action)
  
  
  var modal = $(this)
  modal.find('.modal-title').text('Vas a borrar el departamento con el id: ' + id)
})
}
</script>

@endsection

resources/views/departamento/show.blade.php
@extends('partials.admin')


@section('content')


<div class="row d-flex flex-row">
    <div class="p-2">
        <h3 class="text-primary">{{ $departamento->nombre }}
            <a href="{{ route('departamento.edit',$departamento->id) }}">
                <button class="btn btn-warning btn-circle btn-sm">
                    <i class="fa fw fa-edit"></i>
                </button>
            </a>
        </h3>

    </div>

    <div class="ml-auto p-2 d-flex align-items-center">
        <a href="{{ route('departamento.index') }}">
            <button class="btn btn-info btn-circle"><i class="fa fw fa-arrow-left"></i></button>
        </a>
    </div>

</div> <!-- fin de row -->
@include('partials.session-status')
<div class="row py-2">
    <div class="col-md-12">
        <div class="card shadow border-bottom-info">
            <div class="card-body">
                <label class="control-label">
                    <strong>Nombre:</strong>
                    {{ $departamento->nombre }}
                </label>

                <br>

                <label class="control-label">
                    <strong>Area a la que pertenece:</strong>
                    {{ $departamento->area->nombre }}
                </label>

                <br>

            </div>
        </div>
    </div>
</div> <!-- fin de row -->


@endsection