routes/web.php
<?php


use Illuminate\Support\Facades\Auth;
use Illuminate\Support\Facades\Route;
use App\Http\Controllers\PDFController;
use App\Http\Controllers\AreaController;
use App\Http\Controllers\RoleController;
use App\Http\Controllers\UserController;
use App\Http\Controllers\EventController;
use App\Http\Controllers\PuestoController;
use App\Http\Controllers\EmpresaController;
use App\Http\Controllers\HorarioController;
use App\Http\Controllers\JornadaController;
use App\Http\Controllers\EmpleadoController;
use App\Http\Controllers\HoraExtraController;
use App\Http\Controllers\AsistenciaController;
use App\Http\Controllers\TipoEventoController;
use App\Http\Controllers\DepartamentoController;
use App\Http\Controllers\Auth\RegisterController;
use App\Http\Controllers\IncidenciaHorariaController;


Route::get('/', function () {    
    if (Auth::user() != null) {
        return view('partials.admin');
    }else{
        return view('auth.login');
    }
    
});



Route::get('/admin', function () {
    return view('partials.admin');
});

Route::post('/registrar', [RegisterController::class, 'register'])->name('register.registrar');


//Inasistencia Automatica
Route::get('/inasistencia/add', [IncidenciaHorariaController::class, 'add'])->name('inasistencia.add');

//Empleados
Route::put('/empleadoalta/{empleado}', [EmpleadoController::class, 'alta'])->name('empleado.alta');
Route::get('/empleado/createfind', [EmpleadoController::class, 'createfind'])->name('empleado.createfind');
//Asistencias
Route::get('/asistencia/add', [AsistenciaController::class, 'add'])->name('asistencia.add');
Route::get('/asistencia/marcar', [AsistenciaController::class, 'marcar'])->name('asistencia.marcar');
Route::get('/jornada/editmodal', [JornadaController::class, 'editModal'])->name('jornada.editModal');

//PDF
Route::post('/generate-pdf', [PDFController::class, 'generatePDF'])->name('pdf.generar');
Route::get('/reporte/seleccionar-empleado', [PDFController::class, 'seleccionarEmpleado'])->name('pdf.seleccionar');

//Mis horarios personales
Route::get('/horario/mis_horarios',[HorarioController::class,'indexPersonal'])->name('horario.index_personal');

//Rutas Resource
Route::resource('/empresa', EmpresaController::class);
Route::resource('/area', AreaController::class);
Route::resource('/departamento', DepartamentoController::class);
Route::resource('/puesto', PuestoController::class);
Route::resource('/empleado', EmpleadoController::class);
Route::resource('/tipoevento', TipoEventoController::class);
Route::resource('/horario', HorarioController::class);
Route::resource('/jornada', JornadaController::class);
Route::resource('/horaextra', HoraExtraController::class);
Route::resource('/asistencia', AsistenciaController::class);
Route::resource('/user', UserController::class);
Route::resource('/role', RoleController::class);

//Rutas de Eventos/Incidencias
Route::delete('/event/{event}', [EventController::class, 'destroy'])->name('event.destroy');
Route::post('/event/store', [EventController::class, 'store'])->name('event.store');
Route::get('/event/create', [EventController::class, 'create'])->name('event.create');
Route::get('/event/create2', [EventController::class, 'create2'])->name('event.create2');
Route::get('/event/{event}/edit', [EventController::class, 'edit'])->name('event.edit');
Route::put('/event/{event}', [EventController::class, 'update'])->name('event.update');
Route::get('/event/mostrar', [EventController::class, 'mostrar'])->name('event.mostrar');
Route::get('/event/personal', [EventController::class, 'personal'])->name('event.personal');
Route::get('/eventper', [EventController::class, 'indexper'])->name('event.indexper');
Route::get('/event', [EventController::class, 'index'])->name('event.index');
Route::get('/events', [EventController::class, 'index2'])->name('event.index2');
Route::get('/event/{event}', [EventController::class, 'show'])->name('event.show');
Route::post('/event/editar/{id}', [EventController::class, 'editar'])->name('event.editar');
Route::get('/eventpersonal', [EventController::class, 'indexPersonal'])->name('event.indexpersonal');
Route::get('/eventpersonal/{event}', [EventController::class, 'showPersonal'])->name('event.showpersonal');

//Rutas de incidencias personales
Route::delete('/event2/{event}', [EventController::class, 'destroy2'])->name('event.destroy2');
Route::post('/event/store2', [EventController::class, 'store2'])->name('event.store2');
Route::get('/event/{event}/edit2', [EventController::class, 'edit2'])->name('event.edit2');
Route::put('/event2/{event}', [EventController::class, 'update2'])->name('event.update2');
Route::get('/events2', [EventController::class, 'index3'])->name('event.index3');
Route::get('/event2/{event}', [EventController::class, 'show2'])->name('event.show2');
Route::post('/event/editar/{id}', [EventController::class, 'editar'])->name('event.editar');
Route::get('/eventsall', [EventController::class, 'allIndex'])->name('event.all_index');
Route::get('/eventsall/{event}', [EventController::class, 'showAll'])->name('event.show_all');


//Route::get('/asistencia/marcar/{}', [AsistenciaController::class, 'marcar'])->name('asistencia.marcar');


//Horarios
//Route::get('/horarios-personal', [HorarioController::class, 'indexPersonal'])->name('horario.index_personal');


//Jornada
Route::post('/jornada/add/{horario}', [JornadaController::class, 'add'])->name('jornada.add');
Route::put('/jornada/update2/{jornada}', [JornadaController::class, 'update2'])->name('jornada.update2');




//IncidenciaHoraria-tardanza
Route::get('/incidencia-horaria-personal/index/{flag}', [IncidenciaHorariaController::class, 'indexPersonal'])->name('incidenciahoraria.index_personal');

Route::get('/incidencia-horaria/index/{flag}', [IncidenciaHorariaController::class, 'index'])->name('incidenciahoraria.index');
Route::get('/incidencia-horaria/create/{flag}', [IncidenciaHorariaController::class, 'create'])->name('incidenciahoraria.create');
Route::delete('/incidencia-horaria/{incidenciahoraria}', [IncidenciaHorariaController::class, 'destroy'])->name('incidenciahoraria.destroy');
Route::post('/incidencia-horaria/store', [IncidenciaHorariaController::class, 'store'])->name('incidenciahoraria.store');
Route::get('/incidencia-horaria/{incidenciahoraria}/edit', [IncidenciaHorariaController::class, 'edit'])->name('incidenciahoraria.edit');
Route::put('/incidencia-horaria/{incidenciahoraria}', [IncidenciaHorariaController::class, 'update'])->name('incidenciahoraria.update');
Route::get('/incidencia-horaria-personal/{incidenciahoraria}', [IncidenciaHorariaController::class, 'personal'])->name('incidenciahoraria.personal');
Route::get('/incidencia-horaria/{incidenciahoraria}', [IncidenciaHorariaController::class, 'show'])->name('incidenciahoraria.show');

//IncidenciaHoraria-retiros tempranos

//Ruta de Asistencias
// Index personal
Route::get('/mis-asistencias',[AsistenciaController::class, 'index'])->name('asistencia.index');
// Index general
Route::get('/lista-asistencias',[AsistenciaController::class,'indexAll'])->name('asistencia.indexall');
Route::get('/asistencia/{id}',[AsistenciaController::class, 'show'])->name('asistencia.show');
Route::get('/lista-asistencias/create',[AsistenciaController::class,'create'])->name('asistecia.create');
Route::post('lista-asistencias/store',[AsistenciaController::class,'store'])->name('asistencia.store');
Route::get('lista-asistencias/{asistencia}/edit',[AsistenciaController::class,'edit'])->name('asistencia.edit');
Route::put('lista-asistencias/{asistencia}',[AsistenciaController::class,'update'])->name('asistencia.update');
Route::delete('lista-asistencias/{asistencia}',[AsistenciaController::class,'destroy'])->name('asistencia.destroy');

//Horas Extras
Route::get('/horas-extras-personal', [HoraExtraController::class, 'indexPersonal'])->name('horaextra.index_personal');








Auth::routes();

Route::get('/home', [App\Http\Controllers\HomeController::class, 'index'])->name('home');

app/Models/User.php
<?php

namespace App\Models;

use App\Models\Event;
use App\Models\Empleado;
use Laravel\Sanctum\HasApiTokens;
use Illuminate\Notifications\Notifiable;
use Illuminate\Contracts\Auth\MustVerifyEmail;
use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Foundation\Auth\User as Authenticatable;
use Spatie\Permission\Traits\HasRoles;

class User extends Authenticatable
{
    use HasApiTokens, HasFactory, Notifiable;
    use HasRoles;

    /**
     * The attributes that are mass assignable.
     *
     * @var string[]
     */
    protected $fillable = [
        'name',
        'email',
        'password',
        'empleado_id',
    ];

    /**
     * The attributes that should be hidden for serialization.
     *
     * @var array
     */
    protected $hidden = [
        'password',
        'remember_token',
    ];

    /**
     * The attributes that should be cast.
     *
     * @var array
     */
    protected $casts = [
        'email_verified_at' => 'datetime',
    ];

    public function empleado()
    {
    	return $this->belongsTo(Empleado::class);
    }

    // public function events()
    // {
    //     return $this->hasMany(Event::class);
    // }
}

app/Http/Controllers/UserController.php
<?php

namespace App\Http\Controllers;

use App\Models\User;
use Illuminate\Http\Request;
use Spatie\Permission\Models\Role;

class UserController extends Controller
{

    public function __construct(){
        $this->middleware('can:user.index')->only('index');
        $this->middleware('can:user.edit')->only('edit', 'update');        
    }
    public function index()
    {
        $users = User::orderBy('created_at','desc')->paginate(10);
        return view("user/index",['users' => $users]);
    }

    public function edit(User $user)
    {
        $roles= Role::all();
        // $user = User::get();
        return view("user.edit", ["user" => $user, "roles" => $roles]);
    }

    public function update(Request $request, User $user)
    {
        $user->roles()->sync($request->roles);

        return redirect()->route('user.index')->with('status', 'Roles Asignados');
    }
}

resources/views/user/_form.blade.php
@csrf
<div class="card">
    <div class="card-body">
<div class="row">
{{-- <div class="form-group col-md-6 mb-3">
    <label for="name">Nombre</label>
    <input class="form-control form-control-sm" type="text" name="name" id="name" value="{{ old('name', $user->name)}}">

    @error('name')
    <small class="text-danger">{{ $message }}</small>
    @enderror   

</div> --}}
</div>

<div class="row">
    <div class="form-group col-md-6 mb-3">
        <label for="roles">Roles</label>
        @foreach ($roles as $role)
            <div>
                <label for="roles[]">
                    <input type="checkbox" name="roles[]" value="{{ $role->id }}" class="mr-1" 
                    @if ($user->roles->contains('id', $role->id))
                        checked
                    @endif>
                    {{ $role->name }}
                </label>
            </div>
        @endforeach
    
        @error('roles')
        <small class="text-danger">{{ $message }}</small>
        @enderror   
    
    </div>
    </div>



<div class="row col-md-6 mb-3">
<input class="btn btn-primary" type="submit" value="Guardar">
</div>

</div>
</div>

resources/views/user/create.blade.php
@extends('partials.admin')


@section('content')
<div class="row d-flex flex-row">
    <div class="p-2">
        <h3 class="text-primary">Registrar un Area</h3>
    </div>
    <div class="ml-auto p-2 d-flex align-items-center">
        <a href="{{ route('area.index') }}">
            <button class="btn btn-info btn-circle"><i class="fa fw fa-arrow-left"></i></button>
        </a>
    </div>
</div>

{{-- @include('partials.validation-error') --}}

<form action="{{  route("area.store")  }}" method="post">
@include('area._form')
</form>

@endsection

resources/views/user/edit.blade.php
@extends('partials.admin')


@section('content')
<div class="row d-flex flex-row">
    <div class="p-2">
        <h3 class="text-primary">Editar un Usuario</h3>
    </div>
    <div class="ml-auto p-2 d-flex align-items-center">
        <a href="{{ route('user.index') }}">
            <button class="btn btn-info btn-circle"><i class="fa fw fa-arrow-left"></i></button>
        </a>
    </div>
</div>
@include('partials.validation-error')
@include('partials.session-status')


<form action="{{  route("user.update", $user->id)  }}" method="post">
    @method('PUT')
    @include('user._form')
</form>
<br>

@endsection

resources/views/user/index.blade.php
@extends('partials.admin')



@section('content')
<div class="row d-flex flex-row">
    <div class="p-2">
        <h3 class="text-primary">Listado de Usuarios</h3>
    </div>
</div>

{{-- <a class="btn btn-success mt-3 mb-3" href="{{ route('empresa.create') }}">Crear</a> --}}


@include('partials.session-status')
@include('partials.session-error')
<p class="alert alert-info d-none d-sm-block animated fadeIn" >
    Desde aquí, podrá <strong>Ver, </strong> o <strong>Modificar Roles</strong> de un Usuario.
</p>
<table class="table table-bordered table-hover table-responsive-sm shadow table-sm">
    <thead class="bg-dark text-white">
        <tr>
            <td>
                Id
            </td>
            <td>
                Nombre
            </td>
            <td>
                Email    
            </td>          
            <td>
                
            </td>
        </tr>
    </thead>
    <tbody>
        @if($users->count() == 0)
            <td style="background-color:gainsboro" colspan="5">No hay usuarios registrados</td>
        @else
       @foreach ( $users as $user)
       <tr>
            <td>
                {{ $user->id }}
            </td>
            <td>
                {{ $user->name }}
            </td>
            <td>
                {{ $user->email }}
            </td>
            <td>
                <div class="d-flex justify-content-center">
                {{-- <a href="{{ route('user.show', $user->id)}}" class="btn btn-primary mr-2 btn-sm"><i class="fa fw fa-info"></i> Ver</a> --}}
                <a href="{{ route('user.edit', $user->id)}}" class="btn btn-info mr-2 btn-sm"><i class="fa fw fa-edit"></i> Editar Roles</a>
                
                {{-- <button type="button" class="btn btn-danger btn-sm" data-toggle="modal" data-target="#deleteModal" data-id="{{ $user->id }}"><i class="fas fa-trash"></i> Eliminar</button> --}}
                </div>
            </td>
        </tr>
        @endforeach
        @endif
    </tbody>
</table>

{{ $users->links() }}

<div class="modal fade" id="deleteModal" tabindex="-1" role="dialog" aria-labelledby="exampleModalLabel"
    aria-hidden="true">
    <div class="modal-dialog" role="document">
        <div class="modal-content">
            <div class="modal-header">
                <h5 class="modal-title" id="modalLabel"></h5>
                <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                    <span aria-hidden="true">&times;</span>
                </button>
            </div>
            <div class="modal-body">
                <p>¿Seguro que desea borrar el registro seleccionado?</p>
            </div>
            <div class="modal-footer">
                <button type="button" class="btn btn-secondary" data-dismiss="modal">Close</button>
                <form  id="formDelete" action="{{ route('user.destroy',0) }}" method="POST" data-action="{{ route('user.destroy',0) }}">
                    @method('DELETE')
                    @csrf
                    <button type="submit" class="btn btn-danger"><i class="fas fa-trash"></i> Eliminar</button>
                </form>
            </div>
        </div>
    </div>
</div>

<script>
    window.onload = function() {
    $('#deleteModal').on('show.bs.modal', function (event) {  
  var button = $(event.relatedTarget) // Button that triggered the modal
  var id = button.data('id') // Extract info from data-* attributes
  // If necessary, you could initiate an AJAX request here (and then do the updating in a callback).
  // Update the modal's content. We'll use jQuery here, but you could use a data binding library or other methods instead.
  action = $('#formDelete').attr('data-action').slice(0,-1)
  action += id
  console.log(action)

  $('#formDelete').attr('action', action)
  
  
  var modal = $(this)
  modal.find('.modal-title').text('Vas a borrar el usuario con el id: ' + id)
})
}
</script>

@endsection

resources/views/user/show.blade.php
@extends('partials.admin')


@section('content')


<div class="row d-flex flex-row">
    <div class="p-2">
        <h3 class="text-primary">{{ $area->nombre }}
            <a href="{{ route('area.edit',$area->id) }}">
                <button class="btn btn-warning btn-circle btn-sm">
                    <i class="fa fw fa-edit"></i>
                </button>
            </a>
        </h3>

    </div>

    <div class="ml-auto p-2 d-flex align-items-center">
        <a href="{{ route('area.index') }}">
            <button class="btn btn-info btn-circle"><i class="fa fw fa-arrow-left"></i></button>
        </a>
    </div>

</div> <!-- fin de row -->
@include('partials.session-status')
<div class="row py-2">
    <div class="col-md-12">
        <div class="card shadow border-bottom-info">
            <div class="card-body">
                <label class="control-label">
                    <strong>Nombre:</strong>
                    {{ $area->nombre }}
                </label>

                <br>

                <label class="control-label">
                    <strong>Empresa a la que pertenece:</strong>
                    {{ $area->empresa->nombre }}
                </label>

                <br>

            </div>
        </div>
    </div>
</div> <!-- fin de row -->


@endsection