routes/web.php
<?php


use Illuminate\Support\Facades\Auth;
use Illuminate\Support\Facades\Route;
use App\Http\Controllers\PDFController;
use App\Http\Controllers\AreaController;
use App\Http\Controllers\RoleController;
use App\Http\Controllers\UserController;
use App\Http\Controllers\EventController;
use App\Http\Controllers\PuestoController;
use App\Http\Controllers\EmpresaController;
use App\Http\Controllers\HorarioController;
use App\Http\Controllers\JornadaController;
use App\Http\Controllers\EmpleadoController;
use App\Http\Controllers\HoraExtraController;
use App\Http\Controllers\AsistenciaController;
use App\Http\Controllers\TipoEventoController;
use App\Http\Controllers\DepartamentoController;
use App\Http\Controllers\Auth\RegisterController;
use App\Http\Controllers\IncidenciaHorariaController;


Route::get('/', function () {    
    if (Auth::user() != null) {
        return view('partials.admin');
    }else{
        return view('auth.login');
    }
    
});



Route::get('/admin', function () {
    return view('partials.admin');
});

Route::post('/registrar', [RegisterController::class, 'register'])->name('register.registrar');


//Inasistencia Automatica
Route::get('/inasistencia/add', [IncidenciaHorariaController::class, 'add'])->name('inasistencia.add');

//Empleados
Route::put('/empleadoalta/{empleado}', [EmpleadoController::class, 'alta'])->name('empleado.alta');
Route::get('/empleado/createfind', [EmpleadoController::class, 'createfind'])->name('empleado.createfind');
//Asistencias
Route::get('/asistencia/add', [AsistenciaController::class, 'add'])->name('asistencia.add');
Route::get('/asistencia/marcar', [AsistenciaController::class, 'marcar'])->name('asistencia.marcar');
Route::get('/jornada/editmodal', [JornadaController::class, 'editModal'])->name('jornada.editModal');

//PDF
Route::post('/generate-pdf', [PDFController::class, 'generatePDF'])->name('pdf.generar');
Route::get('/reporte/seleccionar-empleado', [PDFController::class, 'seleccionarEmpleado'])->name('pdf.seleccionar');

//Mis horarios personales
Route::get('/horario/mis_horarios',[HorarioController::class,'indexPersonal'])->name('horario.index_personal');

//Rutas Resource
Route::resource('/empresa', EmpresaController::class);
Route::resource('/area', AreaController::class);
Route::resource('/departamento', DepartamentoController::class);
Route::resource('/puesto', PuestoController::class);
Route::resource('/empleado', EmpleadoController::class);
Route::resource('/tipoevento', TipoEventoController::class);
Route::resource('/horario', HorarioController::class);
Route::resource('/jornada', JornadaController::class);
Route::resource('/horaextra', HoraExtraController::class);
Route::resource('/asistencia', AsistenciaController::class);
Route::resource('/user', UserController::class);
Route::resource('/role', RoleController::class);

//Rutas de Eventos/Incidencias
Route::delete('/event/{event}', [EventController::class, 'destroy'])->name('event.destroy');
Route::post('/event/store', [EventController::class, 'store'])->name('event.store');
Route::get('/event/create', [EventController::class, 'create'])->name('event.create');
Route::get('/event/create2', [EventController::class, 'create2'])->name('event.create2');
Route::get('/event/{event}/edit', [EventController::class, 'edit'])->name('event.edit');
Route::put('/event/{event}', [EventController::class, 'update'])->name('event.update');
Route::get('/event/mostrar', [EventController::class, 'mostrar'])->name('event.mostrar');
Route::get('/event/personal', [EventController::class, 'personal'])->name('event.personal');
Route::get('/eventper', [EventController::class, 'indexper'])->name('event.indexper');
Route::get('/event', [EventController::class, 'index'])->name('event.index');
Route::get('/events', [EventController::class, 'index2'])->name('event.index2');
Route::get('/event/{event}', [EventController::class, 'show'])->name('event.show');
Route::post('/event/editar/{id}', [EventController::class, 'editar'])->name('event.editar');
Route::get('/eventpersonal', [EventController::class, 'indexPersonal'])->name('event.indexpersonal');
Route::get('/eventpersonal/{event}', [EventController::class, 'showPersonal'])->name('event.showpersonal');

//Rutas de incidencias personales
Route::delete('/event2/{event}', [EventController::class, 'destroy2'])->name('event.destroy2');
Route::post('/event/store2', [EventController::class, 'store2'])->name('event.store2');
Route::get('/event/{event}/edit2', [EventController::class, 'edit2'])->name('event.edit2');
Route::put('/event2/{event}', [EventController::class, 'update2'])->name('event.update2');
Route::get('/events2', [EventController::class, 'index3'])->name('event.index3');
Route::get('/event2/{event}', [EventController::class, 'show2'])->name('event.show2');
Route::post('/event/editar/{id}', [EventController::class, 'editar'])->name('event.editar');
Route::get('/eventsall', [EventController::class, 'allIndex'])->name('event.all_index');
Route::get('/eventsall/{event}', [EventController::class, 'showAll'])->name('event.show_all');


//Route::get('/asistencia/marcar/{}', [AsistenciaController::class, 'marcar'])->name('asistencia.marcar');


//Horarios
//Route::get('/horarios-personal', [HorarioController::class, 'indexPersonal'])->name('horario.index_personal');


//Jornada
Route::post('/jornada/add/{horario}', [JornadaController::class, 'add'])->name('jornada.add');
Route::put('/jornada/update2/{jornada}', [JornadaController::class, 'update2'])->name('jornada.update2');




//IncidenciaHoraria-tardanza
Route::get('/incidencia-horaria-personal/index/{flag}', [IncidenciaHorariaController::class, 'indexPersonal'])->name('incidenciahoraria.index_personal');

Route::get('/incidencia-horaria/index/{flag}', [IncidenciaHorariaController::class, 'index'])->name('incidenciahoraria.index');
Route::get('/incidencia-horaria/create/{flag}', [IncidenciaHorariaController::class, 'create'])->name('incidenciahoraria.create');
Route::delete('/incidencia-horaria/{incidenciahoraria}', [IncidenciaHorariaController::class, 'destroy'])->name('incidenciahoraria.destroy');
Route::post('/incidencia-horaria/store', [IncidenciaHorariaController::class, 'store'])->name('incidenciahoraria.store');
Route::get('/incidencia-horaria/{incidenciahoraria}/edit', [IncidenciaHorariaController::class, 'edit'])->name('incidenciahoraria.edit');
Route::put('/incidencia-horaria/{incidenciahoraria}', [IncidenciaHorariaController::class, 'update'])->name('incidenciahoraria.update');
Route::get('/incidencia-horaria-personal/{incidenciahoraria}', [IncidenciaHorariaController::class, 'personal'])->name('incidenciahoraria.personal');
Route::get('/incidencia-horaria/{incidenciahoraria}', [IncidenciaHorariaController::class, 'show'])->name('incidenciahoraria.show');

//IncidenciaHoraria-retiros tempranos

//Ruta de Asistencias
// Index personal
Route::get('/mis-asistencias',[AsistenciaController::class, 'index'])->name('asistencia.index');
// Index general
Route::get('/lista-asistencias',[AsistenciaController::class,'indexAll'])->name('asistencia.indexall');
Route::get('/asistencia/{id}',[AsistenciaController::class, 'show'])->name('asistencia.show');
Route::get('/lista-asistencias/create',[AsistenciaController::class,'create'])->name('asistecia.create');
Route::post('lista-asistencias/store',[AsistenciaController::class,'store'])->name('asistencia.store');
Route::get('lista-asistencias/{asistencia}/edit',[AsistenciaController::class,'edit'])->name('asistencia.edit');
Route::put('lista-asistencias/{asistencia}',[AsistenciaController::class,'update'])->name('asistencia.update');
Route::delete('lista-asistencias/{asistencia}',[AsistenciaController::class,'destroy'])->name('asistencia.destroy');

//Horas Extras
Route::get('/horas-extras-personal', [HoraExtraController::class, 'indexPersonal'])->name('horaextra.index_personal');








Auth::routes();

Route::get('/home', [App\Http\Controllers\HomeController::class, 'index'])->name('home');

app/Models/Horario.php
<?php

namespace App\Models;

use App\Models\Jornada;
use App\Models\Empleado;
use App\Models\CategoriaHorario;
use Illuminate\Database\Eloquent\Model;
use Illuminate\Database\Eloquent\Factories\HasFactory;

class Horario extends Model
{
    Protected $fillable = ['nombre','tolerancia','categoria_id'];

    public function jornadas()
    {
        return $this->hasMany(Jornada::class);
    }

    public function categoria()
    {
        return $this->belongsTo(CategoriaHorario::class);
    }

    public function empleados()
    {
        return $this->hasMany(Empleado::class);
    }

    use HasFactory;
}

app/Http/Controllers/HorarioController.php
<?php

namespace App\Http\Controllers;

use App\Models\Horario;
use App\Models\Jornada;
use App\Models\Empleado;
use Illuminate\Http\Request;
use App\Models\CategoriaHorario;
use Illuminate\Support\Facades\Auth;
use App\Http\Requests\StoreHorarioPost;
use Illuminate\Support\Facades\Redirect;

class HorarioController extends Controller
{

    public function __construct(){
        $this->middleware('can:horario.index')->only('index');
        $this->middleware('can:horario.edit')->only('edit', 'update');
        $this->middleware('can:horario.destroy')->only('destroy');
        $this->middleware('can:horario.create')->only('create', 'store');
        $this->middleware('can:horario.show')->only('show');
    }
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        $horarios = Horario::orderBy('created_at','desc')->paginate(10);
        return view("horario/index",['horarios' => $horarios]);
    }

    public function indexPersonal()
    {
        $user = auth()->user();
        $empleado = Empleado::find($user->empleado_id);
        $horario = $empleado->horario()->first();
        $jornadas = Jornada::where('horario_id',$horario->id)->get();

        // Obtengo todos los horarios del empleado
        $lunes = Jornada::where('horario_id', $horario->id)->where('isLunes',1)->get();
        $martes = Jornada::where('horario_id', $horario->id)->where('isMartes',1)->get();
        $miercoles = Jornada::where('horario_id', $horario->id)->where('isMiercoles',1)->get();
        $jueves = Jornada::where('horario_id', $horario->id)->where('isJueves',1)->get();
        $viernes = Jornada::where('horario_id', $horario->id)->where('isViernes',1)->get();
        $sabado = Jornada::where('horario_id', $horario->id)->where('isSabado',1)->get();
        $domingo = Jornada::where('horario_id', $horario->id)->where('isDomingo',1)->get();
        
        return view("horario/listaHorarioPersonal",['jornadas'=>$jornadas, 'lunes' => $lunes, 'martes' => $martes, 'miercoles' => $miercoles, 'jueves' => $jueves,'viernes' => $viernes,'sabado' => $sabado,'domingo' => $domingo ]);
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        $categorias = CategoriaHorario::get();

        return view("horario/create",["horario" => new Horario(), "categorias" => $categorias]);
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(StoreHorarioPost $request)
    {
        $horario = Horario::create($request->validated());
        //return Redirect::to("horario")->with('status','Horario Creado Exitosamente');
        return redirect()->route('horario.show', $horario);    

    }

    /**
     * Display the specified resource.
     *
     * @param  \App\Models\Horario  $horario
     * @return \Illuminate\Http\Response
     */
    public function show(Horario $horario)
    {
        return view("horario.show", ["horario" => $horario]);
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  \App\Models\Horario  $horario
     * @return \Illuminate\Http\Response
     */
    public function edit(Horario $horario)    {
        
        $categorias = CategoriaHorario::get();
        return view("horario.edit", ["horario" => $horario, "categorias" => $categorias]);
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  \App\Models\Horario  $horario
     * @return \Illuminate\Http\Response
     */
    public function update(StoreHorarioPost $request, Horario $horario)
    {
        $horario->update($request->validated());
        return Redirect::to("horario")->with('status','Horario Actualizado');
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  \App\Models\Horario  $horario
     * @return \Illuminate\Http\Response
     */
    public function destroy(Horario $horario)
    {
        if($horario->empleados->count() == 0){
            foreach ($horario->jornadas as $jornada) {
                $jornada->delete();
            }            
            $horario->delete();
            return back()->with('status','Horario Eliminado');
        }else{
            return back()->with('error','No puede eliminarse el horario ya que tiene información asociada'); 
        }
    }
}

resources/views/horario/_form.blade.php
@csrf
<div class="card">
    <div class="card-body">
<div class="row">
<div class="form-group col-md-3 mb-3">
    <label for="nombre">Nombre</label>
    <input class="form-control form-control-sm" type="text" name="nombre" id="nombre" value="{{ old('nombre', $horario->nombre)}}" required autofocus autocomplete="off"> 

    @error('nombre')
    <small class="text-danger">{{ $message }}</small>
    @enderror   

</div>
</div>


<div class="row">
<div class="form-group col-md-3 mb-3">
    <label for="categoria_id">Categoria</label>
    <select class="form-control form-control-sm" name="categoria_id" id="categoria_id">
        @foreach ($categorias as $categoria)
            <option {{ $horario->categoria_id == $categoria->id ? 'selected="selected"' : ''}} value="{{ $categoria->id}}">{{ $categoria->nombre}}</option>
        @endforeach
    </select>
    
    @error('categoria_id')
    <small class="text-danger">{{ $message }}</small>
    @enderror   
</div>
</div>

<div class="row">
    <div class="form-group col-md-3 mb-3">
        <label for="tolerancia">Tolerancia (minutos)</label>
        <input class="form-control form-control-sm col-md-3" type="number" min="0" max="60" name="tolerancia" id="tolerancia" value="{{ old('tolerancia', $horario->tolerancia)}}" oninput="this.value = 
        (!!(this.value && Math.abs(this.value) >= 0) ? Math.abs(this.value) : null) && (!!(this.value && Math.abs(this.value) <= 60) ? Math.abs(this.value) : 60)" required autofocus>
    
        @error('tolerancia')
        <small class="text-danger">{{ $message }}</small>
        @enderror   
    
    </div>
</div>

<div class="row col-md-6 mb-3">
<input class="btn btn-primary" type="submit" value="Guardar">
</div>

</div>
</div>

resources/views/horario/create.blade.php
@extends('partials.admin')


@section('content')
<div class="row d-flex flex-row">
    <div class="p-2">
        <h3 class="text-primary">Registrar un Horario</h3>
    </div>
    <div class="ml-auto p-2 d-flex align-items-center">
        <a href="{{ route('horario.index') }}">
            <button class="btn btn-info btn-circle"><i class="fa fw fa-arrow-left"></i></button>
        </a>
    </div>
</div>

{{-- @include('partials.validation-error') --}}

<form action="{{  route("horario.store")  }}" method="post">
@include('horario._form')
</form>

@endsection

resources/views/horario/edit.blade.php
@extends('partials.admin')


@section('content')
<div class="row d-flex flex-row">
    <div class="p-2">
        <h3 class="text-primary">Editar un Horario</h3>
    </div>
    <div class="ml-auto p-2 d-flex align-items-center">
        <a href="{{ route('horario.index') }}">
            <button class="btn btn-info btn-circle"><i class="fa fw fa-arrow-left"></i></button>
        </a>
    </div>
</div>
@include('partials.validation-error')

<form action="{{  route("horario.update", $horario->id)  }}" method="post">
    @method('PUT')
    @include('horario._form')
</form>
<br>

@endsection

resources/views/horario/index.blade.php
@extends('partials.admin')



@section('content')
<div class="row d-flex flex-row">
    <div class="p-2">
        <h3 class="text-primary">Listado de Horarios</h3>
    </div>
</div>

{{-- <a class="btn btn-success mt-3 mb-3" href="{{ route('empresa.create') }}">Crear</a> --}}


@include('partials.session-status')
@include('partials.session-error')
<p class="alert alert-info d-none d-sm-block animated fadeIn" >
    Desde aquí, podrá <strong>crear, editar</strong> o <strong>dar de baja</strong> un Horario.
</p>
<table class="table table-bordered table-hover table-responsive-sm shadow table-sm">
    <thead class="bg-dark text-white">
        <tr>
            <td>
                Id
            </td>
            <td>
                Nombre
            </td>
            <td>
                Tolerancia    
            </td>
            <td>
                Categoría
            </td>          
            <td>
                <div class="d-flex justify-content-center">
                    <a href="{{ route('horario.create') }}" >
                        <button class="btn btn-success btn-sm" type="button"><i class="fa fw fa-plus"></i> Nuevo</button>
                    </a>
                </div>
            </td>
        </tr>
    </thead>
    <tbody>
        @if($horarios->count() == 0)
            <td style="background-color:gainsboro" colspan="5">No hay horarios registrados</td>
        @else
       @foreach ( $horarios as $horario)
       <tr>
            <td>
                {{ $horario->id }}
            </td>
            <td>
                {{ $horario->nombre }}
            </td>
            <td>
                {{ $horario->tolerancia }} min.
            </td>
            <td>
                {{ $horario->categoria->nombre }}
            </td>
            <td>
                <div class="d-flex justify-content-center">
                <a href="{{ route('horario.show', $horario->id)}}" class="btn btn-primary mr-2 btn-sm"><i class="fa fw fa-info"></i> Ver</a>
                <a href="{{ route('horario.edit', $horario->id)}}" class="btn btn-warning mr-2 btn-sm"><i class="fa fw fa-edit"></i> Editar</a>
                
                <button type="button" class="btn btn-danger btn-sm" data-toggle="modal" data-target="#deleteModal" data-id="{{ $horario->id }}"><i class="fas fa-trash"></i> Eliminar</button>
                </div>
            </td>
        </tr>
        @endforeach
        @endif
    </tbody>
</table>

{{ $horarios->links() }}

<div class="modal fade" id="deleteModal" tabindex="-1" role="dialog" aria-labelledby="exampleModalLabel"
    aria-hidden="true">
    <div class="modal-dialog" role="document">
        <div class="modal-content">
            <div class="modal-header">
                <h5 class="modal-title" id="modalLabel"></h5>
                <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                    <span aria-hidden="true">&times;</span>
                </button>
            </div>
            <div class="modal-body">
                <p>¿Seguro que desea borrar el registro seleccionado?</p>
            </div>
            <div class="modal-footer">
                <button type="button" class="btn btn-secondary" data-dismiss="modal">Close</button>
                <form  id="formDelete" action="{{ route('horario.destroy',0) }}" method="POST" data-action="{{ route('horario.destroy',0) }}">
                    @method('DELETE')
                    @csrf
                    <button type="submit" class="btn btn-danger"><i class="fas fa-trash"></i> Eliminar</button>
                </form>
            </div>
        </div>
    </div>
</div>

<script>
    window.onload = function() {
    $('#deleteModal').on('show.bs.modal', function (event) {  
  var button = $(event.relatedTarget) // Button that triggered the modal
  var id = button.data('id') // Extract info from data-* attributes
  // If necessary, you could initiate an AJAX request here (and then do the updating in a callback).
  // Update the modal's content. We'll use jQuery here, but you could use a data binding library or other methods instead.
  action = $('#formDelete').attr('data-action').slice(0,-1)
  action += id
  console.log(action)

  $('#formDelete').attr('action', action)
  
  
  var modal = $(this)
  modal.find('.modal-title').text('Vas a borrar el horario con el id: ' + id)
})
}
</script>

@endsection

resources/views/horario/listaHorarioPersonal.blade.php
@extends('partials.admin')

@section('content')

<div class="row d-flex flex-row">
    <div class="p-2">
        <h3 class="text-primary">Mis Horarios</h3>
    </div>
</div>

@include('partials.session-status')
@include('partials.session-error')
<p class="alert alert-info d-none d-sm-block animated fadeIn" >
    Desde aquí, podrá <strong>ver todas sus horarios de trabajo en la semana</strong>.
</p>

<div class="row py-2">
    @if ($jornadas->count() != 0)
        {{-- Lunes --}}
        @if ($lunes->count() != 0)
        <div class="col-md-12 mb-3">
            <div class="card shadow border-left-primary">
                <div class="card-body">
                    <div class="card-title"><b>Lunes</b></div>
                    <ul>
                        @foreach ($lunes as $l)
                            <li> {{$l->entrada}} - {{$l->salida}}</li>
                        @endforeach
                    </ul>
                </div>
            </div>
        </div>    
        @endif
        

        {{-- Martes --}}
        @if ($martes->count()!=0)
        <div class="col-md-12 mb-3">
            <div class="card shadow border-left-success">
                <div class="card-body">
                    <div class="card-title"><b>Martes</b></div>
                    <ul>
                        @foreach ($martes as $mar)
                            <li> {{$mar->entrada}} - {{$mar->salida}}</li>
                        @endforeach
                    </ul>
                </div>
            </div>
        </div>
        @endif

        {{-- Miercoles --}}
        @if ($miercoles->count()!=0)
        <div class="col-md-12 mb-3">
            <div class="card shadow border-left-info">
                <div class="card-body">
                    <div class="card-title"><b>Miercoles</b></div>
                    <ul>
                        @foreach ($miercoles as $mier)
                            <li> {{$mier->entrada}} - {{$mier->salida}}</li>
                        @endforeach
                    </ul>
                </div>
            </div>
        </div>
        @endif

        {{-- Jueves --}}
        @if ($jueves->count()!=0)
        <div class="col-md-12 mb-3">
            <div class="card shadow border-left-warning">
                <div class="card-body">
                    <div class="card-title"><b>Jueves</b></div>
                    <ul>
                        @foreach ($jueves as $j)
                            <li> {{$j->entrada}} - {{$j->salida}}</li>
                        @endforeach
                    </ul>
                </div>
            </div>
        </div> 
        @endif
        

        {{-- Viernes --}}
        @if ($viernes->count()!=0)
        <div class="col-md-12 mb-3">
            <div class="card shadow border-left-danger">
                <div class="card-body">
                    <div class="card-title"><b>Viernes</b></div>
                    <ul>
                        @foreach ($viernes as $v)
                            <li> {{$v->entrada}} - {{$v->salida}}</li>
                        @endforeach
                    </ul>
                </div>
            </div>
        </div>  
        @endif
        

        {{-- Sabado --}}
        @if ($sabado->count()!=0)
        <div class="col-md-12 mb-3">
            <div class="card shadow border-left-primary">
                <div class="card-body">
                    <div class="card-title"><b>Sabado</b></div>
                    <ul>
                        @foreach ($sabado as $s)
                            <li> {{$s->entrada}} - {{$s->salida}}</li>
                        @endforeach
                    </ul>
                </div>
            </div>
        </div>
        @endif
        

        {{-- Domingo --}}
        @if ($domingo->count()!=0)
        <div class="col-md-12 mb-3">
            <div class="card shadow border-left-success">
                <div class="card-body">
                    <div class="card-title"><b>Domingo</b></div>
                    <ul>
                        @foreach ($domingo as $d)
                            <li> {{$d->entrada}} - {{$d->salida}}</li>
                        @endforeach
                    </ul>
                </div>
            </div>
        </div>
        @endif
        
    @else
        <div class="col-md-12 mb-3">
            <u><b>No posee horarios disponibles</b></u>
        </div>
    @endif
    
</div>


@endsection